/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AttendanceRecord = IDL.Record({
  'studentId' : IDL.Text,
  'present' : IDL.Bool,
  'date' : IDL.Text,
});
export const ExamResult = IDL.Record({
  'total' : IDL.Nat,
  'studentId' : IDL.Text,
  'subject' : IDL.Text,
  'date' : IDL.Text,
  'score' : IDL.Nat,
  'examId' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Text,
  'read' : IDL.Bool,
  'message' : IDL.Text,
});
export const StudentProfile = IDL.Record({
  'id' : IDL.Text,
  'dob' : IDL.Text,
  'name' : IDL.Text,
  'parentId' : IDL.Text,
  'className' : IDL.Text,
});
export const StudyMaterial = IDL.Record({
  'id' : IDL.Text,
  'subject' : IDL.Text,
  'description' : IDL.Text,
  'className' : IDL.Text,
  'fileUrl' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Assignment = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'dueDate' : IDL.Text,
  'description' : IDL.Text,
  'className' : IDL.Text,
});
export const TeacherAnnouncement = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'associatedStudentId' : IDL.Opt(IDL.Text),
});
export const Exam = IDL.Record({
  'id' : IDL.Text,
  'subject' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'className' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAttendance' : IDL.Func([AttendanceRecord], [], []),
  'addExamResult' : IDL.Func([ExamResult], [], []),
  'addNotification' : IDL.Func([IDL.Text, Notification], [], []),
  'addStudentProfile' : IDL.Func([StudentProfile], [], []),
  'addStudyMaterial' : IDL.Func([StudyMaterial], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAssignment' : IDL.Func([Assignment], [], []),
  'getAllStudentProfiles' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(TeacherAnnouncement)], ['query']),
  'getAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
  'getAttendance' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExamResults' : IDL.Func([IDL.Text], [IDL.Vec(ExamResult)], ['query']),
  'getExams' : IDL.Func([], [IDL.Vec(Exam)], ['query']),
  'getNotifications' : IDL.Func([IDL.Text], [IDL.Vec(Notification)], ['query']),
  'getStudentProfile' : IDL.Func([IDL.Text], [StudentProfile], ['query']),
  'getStudyMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'postAnnouncement' : IDL.Func([TeacherAnnouncement], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'scheduleExam' : IDL.Func([Exam], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AttendanceRecord = IDL.Record({
    'studentId' : IDL.Text,
    'present' : IDL.Bool,
    'date' : IDL.Text,
  });
  const ExamResult = IDL.Record({
    'total' : IDL.Nat,
    'studentId' : IDL.Text,
    'subject' : IDL.Text,
    'date' : IDL.Text,
    'score' : IDL.Nat,
    'examId' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Text,
    'read' : IDL.Bool,
    'message' : IDL.Text,
  });
  const StudentProfile = IDL.Record({
    'id' : IDL.Text,
    'dob' : IDL.Text,
    'name' : IDL.Text,
    'parentId' : IDL.Text,
    'className' : IDL.Text,
  });
  const StudyMaterial = IDL.Record({
    'id' : IDL.Text,
    'subject' : IDL.Text,
    'description' : IDL.Text,
    'className' : IDL.Text,
    'fileUrl' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Assignment = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'dueDate' : IDL.Text,
    'description' : IDL.Text,
    'className' : IDL.Text,
  });
  const TeacherAnnouncement = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'associatedStudentId' : IDL.Opt(IDL.Text),
  });
  const Exam = IDL.Record({
    'id' : IDL.Text,
    'subject' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'className' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAttendance' : IDL.Func([AttendanceRecord], [], []),
    'addExamResult' : IDL.Func([ExamResult], [], []),
    'addNotification' : IDL.Func([IDL.Text, Notification], [], []),
    'addStudentProfile' : IDL.Func([StudentProfile], [], []),
    'addStudyMaterial' : IDL.Func([StudyMaterial], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAssignment' : IDL.Func([Assignment], [], []),
    'getAllStudentProfiles' : IDL.Func(
        [],
        [IDL.Vec(StudentProfile)],
        ['query'],
      ),
    'getAnnouncements' : IDL.Func(
        [],
        [IDL.Vec(TeacherAnnouncement)],
        ['query'],
      ),
    'getAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
    'getAttendance' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExamResults' : IDL.Func([IDL.Text], [IDL.Vec(ExamResult)], ['query']),
    'getExams' : IDL.Func([], [IDL.Vec(Exam)], ['query']),
    'getNotifications' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getStudentProfile' : IDL.Func([IDL.Text], [StudentProfile], ['query']),
    'getStudyMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'postAnnouncement' : IDL.Func([TeacherAnnouncement], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'scheduleExam' : IDL.Func([Exam], [], []),
  });
};

export const init = ({ IDL }) => { return []; };