/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Assignment {
  'id' : string,
  'title' : string,
  'dueDate' : string,
  'description' : string,
  'className' : string,
}
export interface AttendanceRecord {
  'studentId' : string,
  'present' : boolean,
  'date' : string,
}
export interface Exam {
  'id' : string,
  'subject' : string,
  'date' : string,
  'description' : string,
  'className' : string,
}
export interface ExamResult {
  'total' : bigint,
  'studentId' : string,
  'subject' : string,
  'date' : string,
  'score' : bigint,
  'examId' : string,
}
export interface Notification {
  'id' : string,
  'date' : string,
  'read' : boolean,
  'message' : string,
}
export interface StudentProfile {
  'id' : string,
  'dob' : string,
  'name' : string,
  'parentId' : string,
  'className' : string,
}
export interface StudyMaterial {
  'id' : string,
  'subject' : string,
  'description' : string,
  'className' : string,
  'fileUrl' : string,
}
export interface TeacherAnnouncement {
  'id' : string,
  'title' : string,
  'content' : string,
  'date' : string,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'associatedStudentId' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAttendance' : ActorMethod<[AttendanceRecord], undefined>,
  'addExamResult' : ActorMethod<[ExamResult], undefined>,
  'addNotification' : ActorMethod<[string, Notification], undefined>,
  'addStudentProfile' : ActorMethod<[StudentProfile], undefined>,
  'addStudyMaterial' : ActorMethod<[StudyMaterial], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAssignment' : ActorMethod<[Assignment], undefined>,
  'getAllStudentProfiles' : ActorMethod<[], Array<StudentProfile>>,
  'getAnnouncements' : ActorMethod<[], Array<TeacherAnnouncement>>,
  'getAssignments' : ActorMethod<[], Array<Assignment>>,
  'getAttendance' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExamResults' : ActorMethod<[string], Array<ExamResult>>,
  'getExams' : ActorMethod<[], Array<Exam>>,
  'getNotifications' : ActorMethod<[string], Array<Notification>>,
  'getStudentProfile' : ActorMethod<[string], StudentProfile>,
  'getStudyMaterials' : ActorMethod<[], Array<StudyMaterial>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'postAnnouncement' : ActorMethod<[TeacherAnnouncement], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'scheduleExam' : ActorMethod<[Exam], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];